<?php
    function groceries_menu()
    {
        $items = array();

        $items['groceries'] = array(
        'title' => 'My grocery list',
        'page callback' => 'grocery_list',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        );
        
        return $items;
    }

    function grocery_list()
    {
        $my_list["eggs"] = array(
        'price' => 5.00,
        'quantity' => 2,
        );

        $my_list["milk"] = array(
        'price' => 3.50,
        'quantity' => 1,
        );

        $my_list["bread"] = array(
        'price' => 1.99,
        'quantity' => 4,
        );

        $groceries = $my_list;
        $list = "";
        $prices = [];
        $quantities = [];
        $sub_total_array =[];
        $sub_total = 0;
        $total = 0;

        foreach ($groceries as $grocery => $grocery_info) {
            $list .= "<li>" . $grocery . "</li>";
            foreach($groceries[$grocery] as $item => $value){
                if ($item == 'price') {
                    array_push($prices, $value);
                    $list .= "<li> Price: " . $value . "</li>";
                } else {
                    array_push($quantities, $value);
                    $list .= "<li> Quantity: " . $value . "</li>";
                    for($i = 0; $i < count($prices); $i++){
                    $sub_total = $prices[$i] * $quantities[$i];
                    }
                }
            }
            $list .= "<li>Subtotal:" . $sub_total . "</li>";
            array_push($sub_total_array, $sub_total);
        }

        foreach ($sub_total_array as $price) {
            $total = $total + $price;
        }

        $list .= "<li>Total Cost:" . $total . "</li>";
        return $list;
    }
