<?php



function commentbuddy_menu() {
        $items = array();
        $items['commentbuddy'] = array(
            'title' => 'Comment Buddy',
            'access callback' => TRUE,
        );
        return $items;
    }

    // function flash_message() {
    //
    //     drupal_set_message("Hi there!");
    //     return "placeholder";
    // }

    function commentbuddy_comment_insert() {

      return drupal_set_message("success");
    }
    function commentbuddy_comment_update() {

      return drupal_set_message("updated");
    }

    function commentbuddy_comment_delete() {

      return drupal_set_message("deleted");
    }
