<?php

function commentbuddy_menu() {
  $items = array();

  $items['examples/form-example'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Comments', //page title
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('commentbuddy_form'), //put the name of the form here
    'access callback' => TRUE
  );

  return $items;
}

function commentbuddy_form($form, &$form_state) {

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => 'Enter your comment',
    '#size' => 10,
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Click Here!'),
  );

  return $form;
}

function commentbuddy_form_validate($form, &$form_state) {
  drupal_set_message("Hi there! Validate");
}

function commentbuddy_form_submit($form, &$form_state) {
  drupal_set_message("Hi there! Submit");
}
?>
